In [1]:
import sys
sys.path.append('/home/lessa/smodels')
from smodels.experiment.databaseObj import Database
from smodels.tools.physicsUnits import GeV,fb,pb
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

In [2]:
db = Database('/home/lessa/smodels-database-old')

In [3]:
exp = db.getExpResults(analysisIDs=['ATLAS-CONF-2013-037'],dataTypes=['upperLimit'],txnames=['T6bbWW'],
                       useSuperseded=True,useNonValidated=True)[0]

In [4]:
tx = exp.getTxNames()[0]
print tx

T6bbWW


In [6]:
m = [[360.430955884*GeV, 128.344970653*GeV*2,128.344970653*GeV]]*2
porig = tx.txnameData.flattenMassArray(m)
print 'porig=',porig
pt = ( (np.matrix(porig)[0] - tx.txnameData.delta_x ) ).tolist()[0]
print pt
pt = np.dot(pt,tx.txnameData._V)  ## rotate
print pt
pt = np.array(pt[:tx.txnameData.dimensionality])
print 'Pt=',pt,'val=',tx.txnameData.getValueFor(m)
# fig = plt.figure()
# ax = fig.add_subplot(111, projection='3d')
# ptm = [pt[0],pt[1],tx.txnameData.getValueFor(m).asNumber(pb)]
# ax.scatter([ptm[0]], [ptm[1]], [ptm[2]],c='r',marker='o')
xpts = []
ypts = []
zpts = []
for ipt in tx.txnameData.tri.simplices[tx.txnameData.tri.find_simplex(pt)]:
    xpts.append(tx.txnameData.tri.points[ipt][0])
    ypts.append(tx.txnameData.tri.points[ipt][1])
    if tx.txnameData.dimensionality == 3:
        zpts.append(tx.txnameData.tri.points[ipt][2])
    else:
        zpts.append(tx.txnameData.xsec[ipt])
    print tx.txnameData.tri.points[ipt],tx.txnameData.xsec[ipt]

porig= [360.430955884, 256.689941306, 128.344970653, 360.430955884, 256.689941306, 128.344970653]
[13.35403280707692, 90.68994130599998, 56.79112449915384, 13.35403280707692, 90.68994130599998, 56.79112449915384]
[  5.15858238e+01   1.43508858e+02   7.52002134e-01  -4.67959005e-14
   0.00000000e+00   1.42108547e-14]
Pt= [  51.58582378  143.50885762    0.75200213] val= 6.51E-01 [pb]
[ 74.08514263 -14.25279427 -45.16991228] 7.40E-01 
[  52.04754142  213.24550128    7.35503086] 6.40E-01 
[ 17.75172964  59.6930145   -8.31120985] 8.20E-01 
[ 121.03363786  197.74849625    8.22757466] 3.20E-01 


In [ ]:
for pt in tx.txnameData._data:
    print pt[0][0],pt[1]

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(xpts, ypts, zpts,s=80,c='r',marker='o')
ax.scatter([pt[0]],[pt[1]],[pt[2]],s=80,c='b',marker='o')
ax.set_xlabel('x')
ax.set_ylabel('y')
if tx.txnameData.dimensionality == 3:
    ax.set_zlabel('UL')
else:
    ax.set_zlabel('z')

plt.show()

In [ ]:
uvw = [pt[:3]]
fill_value=np.nan
tol = sys.float_info.epsilon * 1e06
simplex = tx.txnameData.tri.find_simplex(uvw, tol=tol)
vertices = np.take(tx.txnameData.tri.simplices, simplex, axis=0)
temp = np.take(tx.txnameData.tri.transform, simplex, axis=0)
d=temp.shape[2]
delta = uvw - temp[:, d]
bary = np.einsum('njk,nk->nj', temp[:, :d, :], delta)
tx.txnameData.vtx = vertices
tx.txnameData.wts = np.hstack((bary, 1 - bary.sum(axis=1, keepdims=True)))
v=tx.txnameData.xsec
if type(tx.txnameData.xsec[0]) == float:
    values = np.array ( [ float(x) for x in tx.txnameData.xsec ] )
else:
    values = np.array ( [ x.asNumber() for x in tx.txnameData.xsec ] )
print 'v=',tx.txnameData.wts
ret = np.einsum('nj,nj->n', np.take(values, tx.txnameData.vtx), tx.txnameData.wts)
print 'r=',ret
with np.errstate(invalid='ignore'):
    ret[np.any(tx.txnameData.wts < -1e-10, axis=1)] = fill_value
print ret

In [ ]:
fig.clear()
plt.triplot(xpts,ypts)
plt.plot([ptm[0]], [ptm[1]],'ro',xpts,ypts,'bo')
plt.show()

In [ ]:
tri = tx.txnameData.tri
simplex = tri.find_simplex([pt])
vertices = np.take(tri.simplices, simplex, axis=0)
temp = np.take(tri.transform, simplex, axis=0)
d=temp.shape[2]
delta = [pt] - temp[:, d]
bary = np.einsum('njk,nk->nj', temp[:, :d, :], delta)
vtx = vertices
wts = np.hstack((bary, 1 - bary.sum(axis=1, keepdims=True)))
v=tx.txnameData.xsec
values = np.array ( [ x.asNumber() for x in tx.txnameData.xsec ] )
ret = np.einsum('nj,nj->n', np.take(values, vtx), wts)
with np.errstate(invalid='ignore'):
    ret[np.any(wts < -1e-10, axis=1)] = np.nan
print ret[0]

In [ ]:
vertices

In [ ]:
pt

In [ ]:
m = [[347.406576078*GeV,166.767198233*GeV],[347.406576078*GeV,166.767198233*GeV]]
porig = tx.txnameData.flattenMassArray(m)
ptA = ( (np.matrix(porig)[0] - tx.txnameData.delta_x ) ).tolist()[0]
ptA = np.dot(ptA,tx.txnameData._V)  ## rotate
print ptA,tx.txnameData.countNonZeros(ptA)

In [ ]:
print tx.txnameData.getValueFor(m)